FORMAT: 1A

# API - Institución Financiera

SPS Bank API.

# Online SPSFinancial Root [/]

Index of API SPS Financial resources.

## Group Branches

Resources for Branches.

## Branches [/spsbank/{branchID}]

An SPS Financial has the following fields:

- Branch Identifier
- Branch Name
- Branch Zone
- URL

+ Parameters
    + branchID: 1 (required, string) - Branch ID

### Get all Branches [GET /spsbank]

+ Response 200 (application/json)

                {
                    "Branches": [
                        {
                            "branchID": 1,
                            "name": "Iztapalapa",
                            "zone": "Sur",
                            "image_url": "http://www.iztapalapa.cdmx.gob.mx/images/logos/logoizta.png"
                        }, {
                            "branchID": 2,
                            "name": "Coyoacan",
                            "zone": "Sur",
                            "image_url": "http://coyoacan.df.gob.mx/wp-content/uploads/2015/11/fofacebooklogo.jpg"
                        }, {
                            "branchID": 3,
                            "name": "Tlalpan",
                            "zone": "Sur",
                            "image_url": "https://pbs.twimg.com/profile_images/425327536365502464/8KTlnqQX_400x400.png"
                        }
                    ]
                }
                
### Get Downtown branches details [GET /spsbank/1]

+ Response 200 (application/json)

                {
                    "branchID": 1,
                    "name": "Iztacalco",
                    "zone": "Sur"
                }
                        
### Get North  details [GET /spsbank/2]

+ Response 200 (application/json)

                {
                    "branchID": 2,
                    "name": "Coyoacan",
                    "zone": "Sur"
                }

### Get South SPSPharmacy details [GET /spsbank/3]

+ Response 200 (application/json)

                {
                    "branchID": 3,
                    "name": "Coyoacan",
                    "zone": "Sur"
                }
                

### Get SPSBank by ZipCode 11000 [GET /spsbank/zipcode/11000]

+ Response 200 (application/json)

                {
                    "branchID": 1,
                    "name": "Lomas de Chapultepec-Montes",
                    "zone": "Centro"
                }
                
### Get SPSBank from ZipCode 09730 [GET /spsbank/zipcode/09730]

+ Response 200 (application/json)

                {
                    "branchID": 5,
                    "name": "Vallejo",
                    "zone": "Oriente"
                }
                
### Get SPSBank from ZipCode 54020 [GET /spsbank/zipcode/54020]

+ Response 200 (application/json)

                {
                    "branchID": 2,
                    "name": "Arboledas",
                    "zone": "Norte"
                }
                
### Get credit product availability [GET /spsbank/product/credito]

+ Response 200 (application/json)

                {
                  "Branches": [
                      {
                        "branchID": "1",
                        "name": "SPSBank - Downtown",
                        "zone": "Downtown",
                        "quantity": "0"
                      },
                      {
                        "branchID": "2",
                        "name": "SPSBank - North",
                        "zone": "North",
                        "quantity": "0"
                      },
                      {
                        "branchID": "3",
                        "name": "SPSBank - South",
                        "zone": "South",
                        "quantity": "4"
                      }
                    ]
                }
                
### Get loan availability [GET /spsbank/product/prestamo]

+ Response 200 (application/json)

                {
                  "Branches": [
                      {
                        "branchID": "1",
                        "name": "SPSBank - Downtown",
                        "zone": "Downtown",
                        "quantity": "1"
                      },
                      {
                        "branchID": "2",
                        "name": "SPSBank - North",
                        "zone": "North",
                        "quantity": "6"
                      },
                      {
                        "branchID": "3",
                        "name": "SPSBank - South",
                        "zone": "South",
                        "quantity": "17"
                      },
                      {
                        "branchID": "4",
                        "name": "SPSBank - West",
                        "zone": "West",
                        "quantity": "8"
                      },
                      {
                        "branchID": "5",
                        "name": "SPSBank - East",
                        "zone": "East",
                        "quantity": "7"
                      }
                    ]
                }
                
### Submit a complain [POST /spsbank/complain]

+ Request (application/json)

        [
            {
              "order": {
                "branchID": "1",
                "item": "aspirin",
                "quantity": "3"
              }
            }
        ]
        
+ Response 200 (application/json)

                {
                    "message": "Tu queja ha sido recibida"
                }
