FORMAT: 1A

# SPSBank. Institucion Financiera

SPS Bank API.

## Branches [/spsbank]

With this resource we can get the entire list of branches.

A branch is conformed by:

- BranchID
- Name
- Zone
- Logo

### Get all Branches [GET /spsbank]

+ Response 200 (application/json)

                {
                    "Branches": [
                        {
                            "branchID": 1,
                            "name": "Iztapalapa",
                            "zone": "Sur",
                            "image_url": "http://www.iztapalapa.cdmx.gob.mx/images/logos/logoizta.png"
                        }, {
                            "branchID": 2,
                            "name": "Coyoacan",
                            "zone": "Sur",
                            "image_url": "http://coyoacan.df.gob.mx/wp-content/uploads/2015/11/fofacebooklogo.jpg"
                        }, {
                            "branchID": 3,
                            "name": "Polanco",
                            "zone": "Centro",
                            "image_url": "https://pbs.twimg.com/profile_images/425327536365502464/8KTlnqQX_400x400.png"
                        }
                    ]
                }

## Branch by ID [/spsbank/branch/{branchID}]

With this resource we can get the details of an specific branhk. Thse details are:

- Branche Name
- Branch Location
- Branch logo

+ Parameters
    + branchID: 1 (required, string) - Branch ID


### Get Downtown details [GET /spsbank/1]

+ Response 200 (application/json)

                {
                    "branchName": "http://www.iztapalapa.cdmx.gob.mx/images/logos/logoizta.png",
                    "branchName": "Iztacalco",
                    "branchLocation": "Sur"
                }
                        
### Get North details [GET /spsbank/2]

+ Response 200 (application/json)

                {
                    "branchLogo": "https://pbs.twimg.com/profile_images/425327536365502464/8KTlnqQX_400x400.png",
                    "branchName": "Coyoacan",
                    "branchLocation": "Sur"
                }

### Get South details [GET /spsbank/3]

+ Response 200 (application/json)

                {
                    "branchName": "http://www.iztapalapa.cdmx.gob.mx/images/logos/logoizta.png",
                    "branchName": "Iztacalco",
                    "branchLocation": "Sur"
                }
                

## Branch by ZipCode [/spsbank/zipcode/{zipNumber}]

With this resource we can query for branches within an specific zipCode

+ Parameters
    + zipNumber: 1 (required, string) - zip number
    
    
### Get SPSBank by ZipCode 11000 [GET /spsbank/zipcode/11000]

+ Response 200 (application/json)

                {
                    "branchID": 1,
                    "name": "Lomas de Chapultepec-Montes",
                    "zone": "Centro"
                }
                
### Get SPSBank by ZipCode 09730 [GET /spsbank/zipcode/09730]

+ Response 200 (application/json)

                {
                    "branchID": 5,
                    "name": "Vallejo",
                    "zone": "Oriente"
                }
                
### Get SPSBank from ZipCode 54020 [GET /spsbank/zipcode/54020]

+ Response 200 (application/json)

                {
                    "branchID": 2,
                    "name": "Arboledas",
                    "zone": "Norte"
                }
                
## Branch product availability [/spsbank/product/{productID}]

With this resource we can check the availability of an specific product in different branches

+ Parameters
    + productID: 1 (required, string) - Product ID                
                
### Get credit product availability [GET /spsbank/product/credit]

+ Response 200 (application/json)

                {
                  "Branches": [
                      {
                        "branchID": "1",
                        "name": "SPSBank - Downtown",
                        "zone": "Downtown",
                        "quantity": "0"
                      },
                      {
                        "branchID": "2",
                        "name": "SPSBank - North",
                        "zone": "North",
                        "quantity": "0"
                      },
                      {
                        "branchID": "3",
                        "name": "SPSBank - South",
                        "zone": "South",
                        "quantity": "4"
                      }
                    ]
                }
                
### Get loan availability [GET /spsbank/product/loan]

+ Response 200 (application/json)

                {
                  "Branches": [
                      {
                        "branchID": "1",
                        "name": "SPSBank - Downtown",
                        "zone": "Downtown",
                        "quantity": "1"
                      },
                      {
                        "branchID": "2",
                        "name": "SPSBank - North",
                        "zone": "North",
                        "quantity": "6"
                      },
                      {
                        "branchID": "3",
                        "name": "SPSBank - South",
                        "zone": "South",
                        "quantity": "17"
                      },
                      {
                        "branchID": "4",
                        "name": "SPSBank - West",
                        "zone": "West",
                        "quantity": "8"
                      },
                      {
                        "branchID": "5",
                        "name": "SPSBank - East",
                        "zone": "East",
                        "quantity": "7"
                      }
                    ]
                }


## Complains [/spsbank/complain]


### Submit a complain [POST /spsbank/complain]

+ Request (application/json)

    + Headers
        
            Authrorization: Basic ABCDE

    + Body
    
            [
                {
                    "complain": {
                    "branchID": "1",
                    "title": "Bad service",
                    "complainDescription": "I spent more than 3 hours and my problem was not solved"
                    }
                }
            ]
        
+ Response 201 (application/json)
        
        {
            "message": "Your complain has been received"
        }
        
        
+ Request (application/json)

        [
            {
              "order": {
                "title": "Bad service",
                "complainDescription": "I spent more than 3 hours and my problem was not solved"
              }
            }
        ]
        
+ Response 500 (application/json)
        
        {
            "message": "There is an error in your request"
        }